name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Run Buildozer Docker to build APK
        run: |
          docker run --rm -v ${{ github.workspace }}:/app kivy/buildozer buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: myapp-apk
          path: bin/*.apk
